### ISSUE TITLE
Lua Error: ...eshark/plugins/steam_controller_usb/setup_dissectors.lua:139: FT_ not yet supported

### ISSUE THREAD

**Issue by clst** [sm-Fifteen/SteamControllerTools#11]
That seems to be all I get when looking at the USB packets in Wireshark 3.0.3 on my Linux system.

**Comment by sm-Fifteen** [comment]
I was having issues with wireshark updates giving me similar error messages last time I was working on this, I'll have to see if there's a way to fix this.

**Comment by clst** [comment]
All I have been able to dig up was this mailing list thread from 10 years ago: https://www.wireshark.org/lists/wireshark-dev/200809/msg00018.html

**Comment by sm-Fifteen** [comment]
Looking at it right now (sorry for the delays, I've been forgetting about this for 2 years now, I even [left comments to specifically remind me about this](https://github.com/sm-Fifteen/SteamControllerTools/blob/master/steam_controller_usb/setup_dissectors.lua#L129)), and this issue is just as weird as I remember.

https://www.wireshark.org/docs/wsdg_html_chunked/lua_module_Field.html

Basically, you have `urbTypeField` on line 130 which is of type `Field` and calling it returns a `FieldInfo` object, which contains information about the data in that field, including its value (hence `urbTypeField().value`). That's the part Wireshark doesn't seem to like very much. Trying to do something like `urbTypeField()()`, which the doc says should be equivelent, results in the same thing.

The type of that field is nothing special either, it's just a type 3 field, ~~which my old notes say correspond to `FT_UINT8`~~ is actually a `CHAR` if you look at `ftypes` mapping in `/usr/share/wireshark/init.lua`. Weirdly enough, `urbTypeField().display` works just fine, and I'm half-tempted to just throw my hands up and use that instead.

The thread you linked would be an interesting lead (it's a *very* similar issue) if it didn't just end there, and the official Wireshark bugtracker doesn't seem to have anything from before 2012 on it.

Looking at the Wireshark code, there [*is* an `FT_CHAR` type in the Lua API](https://code.wireshark.org/review/gitweb?p=wireshark.git;a=blob;f=doc/README.dissector;h=387632a47cb77dece208047019cdd0629ed4ccb8;hb=HEAD#l824), but it's actually fairly recent, with [the commit that introduced it dated from September 2016](https://code.wireshark.org/review/gitweb?p=wireshark.git;a=commit;h=d7fe514fc05e95e3a99fd211768de5abdc3f6486). According to the associated code review, [that commit shipped with Wireshark 2.4](https://code.wireshark.org/review/#/c/17787/), which would make sense considering this dissector used to work just fine for me until an update around that time broke it.

So it looks like it's actually been an issue with Wireshark this entire time!!

Guess I'll have to file a bug report for a 3 year old bug, now.

**Comment by clst** [comment]
Hey no problem, thanks for looking into it at all. I am not a LUA (or wireshark) expert so I didn't know where to begin. Looks like not that many people use custom dissectors ;)

**Comment by sm-Fifteen** [comment]
Looks like there's now a patch for that upstream, though I don't know how long until that makes it into Wireshark.

~~https://code.wireshark.org/review/#/c/34775/~~ (broken URL to the patch, see bug report instead)
https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=16129

**Comment by sm-Fifteen** [comment]
I can confirm that the issue no longer occurs on recent versions of WireShark.
